# Generated by Django 5.0.1 on 2025-05-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
