# Generated by Django 5.2.1 on 2025-05-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço por kg'),
        ),
    ]
