# Generated by Django 5.0.1 on 2025-05-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('wastes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='waste',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='wastes.waste'),
        ),
    ]
