# Generated by Django 5.2.1 on 2025-05-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
